### PR TITLE
Add support for python 3

### PR DESCRIPTION
**Pull request by pipermerriam**
> **This is a work in progress to address #9 which was reported by me.**
### What is wrong

Python 3 support would be nice for those using python 3.
### How was it fixed

_it isn't yet_
#### Cute animal picture

unlikely-sleeping-buddies-animal-friendship-611__605

### CODE REVIEW

**Comment by pipermerriam** [comment]
Notes to self.  Here is what `2to3` would change when run on the codebase.

https://github.com/pipermerriam/xml4h/commit/e96b95cfd9a521a1cdf49b6df4fa2956cee68baf

**Comment by jmurty** [comment]
Thanks for your interest in taking this on. Let me know if I can help and I'll do what I can.

**Comment by pipermerriam** [comment]
I was running into circular import issues in python3 and I'm not in love with the way I fixed it.  a0c0b79167b5a5210268c89b29c0d61b1cb67136

Very open to suggestions on how to fix this a different way.

**Comment by jmurty** [comment]
As horrifically late as it is, I am now doing a migration to Python 3 in https://github.com/jmurty/xml4h/pull/12

**Comment by jmurty** [comment]
Python 3 support added in #12

**Pull request closed without merging**
